server:
  port: 9999
  context-path: /spring-security-oauth-server
spring:
  application:
    name: authorizationServer
  datasource:
    url: jdbc:postgresql://localhost:5432/AUTH_SERVER_DB
    username: rdurgesh
    password: rdurgesh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    zipkin: 
    base-url: http://localhost:7777
  sleuth:
    sampler:
      percentage: 1.0
logging:
  level:
    org.springframework.security: DEBUG