server:
  port: 8888
  context-path: /services
security:
  oauth2:
    client:
      client-id: esm-command-line-interface
      client-secret: esm-command-line-interface-secret
      authorized-grant-types:
        authorization_code,refresh_token,password,client_credentials
      scope:
        employee_read,employee_write,employee_trust
